name: Push templates

on:
  workflow_dispatch:
  push:
    branches:
      - main
      # TODO: remove
      - phorcys420/refactor
    paths:
      - 'deployments/ai.coder.com/**'

permissions:
  contents: read

concurrency:
  group: push-templates-ai-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ai-coder-com:
    name: ai.coder.com
    uses: ./.github/workflows/_push-templates-to-deployment.yml
    with:
      deployment_dir: deployments/ai.coder.com
      coder_url: https://ai.coder.com
      activate: true
    secrets:
      CODER_SESSION_TOKEN: ${{ secrets.CODER_SESSION_TOKEN_AI }}
