name: Push templates

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'deployments/ai.coder.com/**'

permissions:
  contents: read

concurrency:
  group: push-templates-ai.coder.com
  cancel-in-progress: true

jobs:
  test-ai-coder-com:
    name: Test ai.coder.com templates
    uses: ./.github/workflows/_validate-template.yml@phorcys420/ci-updates
    with:
      deployment_dir: deployments/ai.coder.com

  ai-coder-com:
    name: ai.coder.com
    needs: test-ai-coder-com
    uses: ./.github/workflows/_push-templates-to-deployment.yml@phorcys420/ci-updates
    with:
      deployment_dir: deployments/ai.coder.com
      coder_url: https://ai.coder.com
      activate: true
    secrets:
      CODER_SESSION_TOKEN: ${{ secrets.CODER_SESSION_TOKEN_AI }}