name: update-coder-coder-templates

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update_submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository including submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive  # Automatically initializes and updates submodules
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Check for changes and push if needed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Auto-update submodule to the latest commit"
            git push origin main
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
